version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: neuro-db
    restart: always
    environment:
      POSTGRES_USER: neuro
      POSTGRES_PASSWORD: neuro-pass
      POSTGRES_DB: neuro_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: neuro-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://neuro:neuro-pass@postgres:5432/neuro_db
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: neuro-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
